### ISSUE TITLE
설계(Design) 관련 Metrics 측정

### ISSUE THREAD

**Issue by switchover** [RedCA-Family/code-analyst#2]
디자인 또는 아키텍처 관련 code metrics 측정 기능 추가

**Comment by heecheolpark** [comment]
아래의 Metrics 추가 필요합니다.
- 결합도(Coupling) : CBO(Coupling Between Objects), RFC(Response For Class)
                                  Fan-In(출력결합, CE(efferent coupling count)), Fan-Out(입력결합, CA(afferent coupling count))
- 응집도 : LCOM(Lack of cohension of methods)
- 상속 : DIT (depth of inheritance tree), NOC (Number of Children)
- 복잡도 : WMC(weighted methods/class; sum of CC)

**Comment by switchover** [comment]
CK Metrics 추가

**Comment by switchover** [comment]
CK Metrics  추가
